# -*- coding: utf-8 -*-
"""
测试用的源目录夹具：自建一批 ``.lnk``，让测试不再依赖用户桌面。

## 为什么需要它

``tests_add`` 和 ``tests_icons`` 原本默认扫 ``Path.home()/"Desktop"``。
这有两个问题，第二个是这次真踩到的：

1. **换台机器就不成立。** 桌面干净（很多人把图标收进
   ``OneDrive\\桌面`` 或干脆不放快捷方式）时扫出 0 条，测试直接失败，
   而失败原因跟被测代码毫无关系。

2. **测试结果会随用户的桌面漂移。** 这次删掉桌面上那个
   ``Launchpad.lnk`` 之后，两个套件立刻从「PASS」变成
   「AssertionError: 没有任何条目，源目录可能变了」。一个**测试夹具的
   变动**让测试红了 —— 说明它测的不是代码，是环境。

所以默认源目录改成这里生成的临时夹具。真要对着真实目录跑（比如想看
自己桌面上那些应用的实际图标）仍然可以，用 ``--real-source`` 或设
``LAUNCHPAD_SOURCE``。

## 夹具里放什么

指向**真实存在的 Windows 可执行文件**的 ``.lnk`` —— 图标提取要走的
是真链路（从 exe 里抠图标、缓存、落盘），用假的空文件测不到那些。
再加一个 UWP/AUMID 的 ``.lnk``（``shell:AppsFolder\\`` 形式），
因为那类条目的 TargetPath 读不出来、必须靠字节扫描捞 AUMID，是
图标提取和库导入各自的一条独立分支。
"""

import os
import sys
from pathlib import Path

#: 会用到的系统程序。不存在的自动跳过（不同 Windows 版本有差异）。
_TARGETS = [
    ("记事本", r"C:\Windows\System32\notepad.exe"),
    ("画图", r"C:\Windows\System32\mspaint.exe"),
    ("命令提示符", r"C:\Windows\System32\cmd.exe"),
    ("控制面板", r"C:\Windows\System32\control.exe"),
    ("任务管理器", r"C:\Windows\System32\taskmgr.exe"),
    ("字符映射表", r"C:\Windows\System32\charmap.exe"),
    ("远程桌面", r"C:\Windows\System32\mstsc.exe"),
    ("注册表编辑器", r"C:\Windows\regedit.exe"),
]

#: 一个 UWP 应用的 AUMID，用来覆盖「读不出 TargetPath」那条分支。
#: 取不到就跳过（不同机器装的 UWP 不一样）。
_UWP_AUMID = "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"


def available_targets() -> list[tuple[str, Path]]:
    """本机真实存在的目标 (名称, 路径)。"""
    out = []
    for name, raw in _TARGETS:
        p = Path(raw)
        try:
            if p.is_file():
                out.append((name, p))
        except OSError:
            pass
    return out


def make_lnk(path: Path, target, args: str = "", icon: str = "") -> bool:
    """
    造一个 ``.lnk``。``target`` 可以是文件路径，也可以是
    ``shell:...`` 之类的 URI（用来造 UWP 那种条目）。

    用 WScript.Shell，并**每次自己 Dispatch 一次**、用完即弃 ——
    模块级常驻的 COM 对象在解释器退出时被拆解会让进程硬崩
    （这个项目踩过）。另外新建的路径不在壳层缓存里，所以不会出现
    「save() 成功但写回旧内容」那个问题。
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        import win32com.client
        shell = win32com.client.Dispatch("WScript.Shell")
        sc = shell.CreateShortcut(str(path))
        sc.TargetPath = str(target)
        if args:
            sc.Arguments = args
        sc.WorkingDirectory = str(path.parent)
        sc.Description = "Launchpad 测试夹具"
        if icon:
            sc.IconLocation = icon
        sc.save()
        return True
    except Exception as exc:
        print(f"[testfix] 造 {path.name} 失败: {exc}", file=sys.stderr)
        return False


def find_uwp_aumid() -> str:
    """
    本机**真实存在**的 UWP AUMID；一个都没有就返回空串。

    保留这个函数是因为排查时需要确认「本机到底有没有 UWP 应用」——
    实测本机 ``known_aumids()`` 有 369 条，但绝大多数是
    ``Microsoft.AutoGenerated.*`` / ``{GUID}\\path`` 这类，
    ``list_start_apps()`` 里带 aumid 的是 **0** 条，也就是这台机器上
    根本没有可用的 UWP 条目。夹具因此不再造 ``shell:AppsFolder`` 链接
    （见 :func:`build_source` 里那段说明）。
    """
    try:
        from launchpad.addapp import known_aumids
        for aumid in sorted(known_aumids()):
            a = (aumid or "").strip()
            # 只认真正的包标识：Microsoft.<包名>_<发布者>!<应用>
            # 或 Microsoft.<包名>!<应用>。带反斜杠或花括号的是「开始菜单
            # 里的一条文件路径」，不是 AUMID。
            if "!" in a and " " not in a:
                return a
    except Exception as exc:
        print(f"[testfix] 查 UWP AUMID 失败: {exc}", file=sys.stderr)
    return ""


def build_source(folder: Path) -> list[Path]:
    """
    在 ``folder`` 里造一批 ``.lnk``，返回造出来的路径列表。

    不递归 —— 与 ``scan_paths(..., recursive=False)`` 的用法对齐。
    幂等：重复调用会覆盖同名文件，不会越堆越多。

    刻意覆盖三类分支：

    1. **普通文件型**（指向真实系统 exe）—— 图标提取的主链路。
    2. **uid 冲突组**：两个**不同名**的 .lnk 指向**同一 target、同一 args**。
       ``Entry.uid`` 在 target 非空时只哈希 ``target|args``，所以这两条
       必然同 uid。这正是 ``tests_icons`` 里「uid 冲突组存在性」要验的
       前提 —— 缺了它，那几条验 uid 隔离的断言会整段 SKIP。
    3. **UWP / 应用商店**：**不在这里造**，理由见下面那段注释。
       UWP 那条链路由 ``tests_add`` 里用显式记录的专门用例覆盖。
    """
    folder.mkdir(parents=True, exist_ok=True)
    made: list[Path] = []

    for name, target in available_targets():
        p = folder / f"{name}.lnk"
        if make_lnk(p, target):
            made.append(p)

    # ── 2. uid 冲突组 ───────────────────────────────────
    tgts = available_targets()
    if tgts:
        name0, t0 = tgts[0]
        for alias in ("记事本-副本", "记事本-另一个快捷方式"):
            p = folder / f"{alias}.lnk"
            # args 留空：uid 哈希的是 "target|args"，两处都必须相同
            if make_lnk(p, t0):
                made.append(p)

    # ── 3. UWP：这里**不**造假链接 ────────────────────────
    #
    # 试过 `make_lnk(p, f"shell:AppsFolder\\{aumid}")`，实测在本机造出来的
    # 链接 `scan_folder` 读不出 target，被判成「无法读取目标（可能是应用
    # 商店应用或损坏链接）」—— 因为 WScript.Shell 写 `shell:` 前缀时并不
    # 把 AUMID 以 `aumid_from_lnk` 能扫到的形式埋进字节，而
    # `known_aumids()` 里 369 条大多是 `Microsoft.AutoGenerated.*` /
    # `{GUID}\path` 这类，不是真正的 UWP 应用标识。
    #
    # 所以**不放**。理由不是「造不出来就算了」，而是放了更糟：它是一条
    # 解析失败的坏条目，会把 `tests_add` 的「剩余失效条目」计数、
    # `tests_icons` 的解析失败数全部带偏 —— 用一个造不准的夹具去污染
    # 别的断言，是拿可观测性换覆盖率。
    #
    # UWP 那条链路本身有专门覆盖：`tests_add` 里用
    # `scan_uwp_apps_from_start_menu(显式选中的记录)` 和往返断言，
    # 那些不依赖源目录里恰好有个商店链接。
    return made


def default_source(tag: str = "lp") -> Path:
    """
    建一个临时源目录并填好夹具，返回它的路径。

    调用方负责清理（或者不管 —— tempfile 目录在系统临时目录下，
    会被系统定期清）。
    """
    import tempfile
    d = Path(tempfile.mkdtemp(prefix=f"{tag}_src_"))
    made = build_source(d)
    if not made:
        raise RuntimeError(
            f"夹具一个都没造出来（目录 {d}）。本机找不到任何 "
            f"C:\\Windows\\System32 下的目标程序？")
    return d


def real_source() -> Path | None:
    """
    用户真实的源目录（``LAUNCHPAD_SOURCE`` 或桌面），**没有 .lnk 就返回 None**。

    返回 None 而不是那个空目录，是因为「目录存在但里面没有快捷方式」
    对调用方是个陷阱：拿它去扫会得到 0 条，然后在别处以「没有条目」
    的形式炸掉，看着像是被测代码坏了。
    """
    env = os.environ.get("LAUNCHPAD_SOURCE")
    folder = Path(env) if env else (Path.home() / "Desktop")
    try:
        if folder.is_dir() and any(folder.glob("*.lnk")):
            return folder
    except OSError:
        pass
    return None